// src/findings/mod.rs — Kontrak output Finding untuk seluruh tim

use serde::{Deserialize, Serialize};

/// Confidence level of analysis results.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ConfidenceLevel {
    High,
    Medium,
    Low,
}

impl std::fmt::Display for ConfidenceLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfidenceLevel::High => write!(f, "HIGH"),
            ConfidenceLevel::Medium => write!(f, "MEDIUM"),
            ConfidenceLevel::Low => write!(f, "LOW"),
        }
    }
}

/// Output data contract for the entire IDX Sentinel team.
///
/// Generated by [`SectorsClient`] and consumed by:
/// - MCP Server (Role 2)
/// - Alert Engine (Role 3)
/// - Dashboard (Role 4)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Finding {
    /// BEI stock ticker, example: `"BBCA"`.
    pub ticker: String,

    /// Financial indicator name, example: `"net_interest_margin_q"`.
    pub metric_name: String,

    /// Indicator value in the **previous** quarter.
    pub previous_value: f64,

    /// Indicator value in the **current** quarter.
    pub current_value: f64,

    /// Current quarter period, format `"YYYY-QN"`, example: `"2024-Q3"`.
    pub period: String,

    /// Data source, example: `"sectors_api_v2/screener"`.
    pub source: String,

    /// Analysis confidence level.
    pub confidence_level: ConfidenceLevel,
}

impl Finding {
    /// Create a new `Finding` with validated fields.
    pub fn new(
        ticker: impl Into<String>,
        metric_name: impl Into<String>,
        previous_value: f64,
        current_value: f64,
        period: impl Into<String>,
        source: impl Into<String>,
        confidence_level: ConfidenceLevel,
    ) -> Self {
        Self {
            ticker: ticker.into(),
            metric_name: metric_name.into(),
            previous_value,
            current_value,
            period: period.into(),
            source: source.into(),
            confidence_level,
        }
    }

    /// Percentage change in indicator value.
    pub fn delta_pct(&self) -> f64 {
        if self.previous_value == 0.0 {
            return 0.0;
        }
        (self.current_value - self.previous_value) / self.previous_value.abs() * 100.0
    }

    /// Whether there is an improvement compared to the previous period.
    pub fn is_improving(&self) -> bool {
        self.current_value > self.previous_value
    }
}
